Add support for version 4 of the protocol
pierre-24/pytimefliplib pull request #6
Opened 2023-11-10 23:53 UTC by john-craig

Okay so here's the big notes about the changes I made:
- added an optional parameter to the client constructor that will be invoked on disconnect
- `base_char_read` and `base_char_write` now expect a string key for the characteristic
rather than the UUID value itself. This allows them to look up the UUID and expected
lengths of data being read/written from the buffer based on the key, which fixes a bug
I had seen in which reading/writing from the buffer without a specific length for substringing
would grab a bunch of garbage data
- upon setup the library will attempt to detect the firmware revision of the Timeflip
and use the protocols that are appropriate for that version

2023-11-11 09:35 UTC, pierre-24 requested changes
Hello,

I don't have a timeflip v4, so I totally trust you on that one :)

However, there are a few comments that remains from your test, and just to keep the code somehow clean, it would be nice to remove them.

2023-11-11 09:35 UTC, pierre-24 commented on pytimefliplib/scripts/check.py
> +        #await client.set_facet(1,1,300)
Can you remove that one ? :)

2023-11-11 09:35 UTC, pierre-24 commented on pytimefliplib/async_client.py
> +    'event_data':           UUID_TIMEFLIP.format(0x6f51), # vers 4.0
Per pep-008, there should be two-spaces between the comma and the comment :)

2023-11-11 09:35 UTC, pierre-24 commented on pytimefliplib/async_client.py
> +        # elif len(data) != length:
Could you remove that comment?

2023-11-13 16:54 UTC, john-craig commented
Made requested changed to comments. I also tweaked some things that I realized would prevent backwards compatibility to version 3.

2023-11-14 07:27 UTC, pierre-24 commented
Perfect, then :)

2023-11-14 07:28 UTC, merged